### ISSUE TITLE
VS2019 compile error

### ISSUE THREAD

**Issue by lyd405121** [mitsuba-renderer/rgb2spec#4]
- I am starting building a spectrum renderer,and find your article will be exactly I neeed.
- But,  I find an compiler error in rgb2spec_opt.cpp which is line 298
- Error info: error C2059:“(”

```c
#  pragma omp parallel for collapse(2) default(none) schedule(dynamic) shared(stdout,scale,out)
```

So I change it to 

```c
#  pragma omp parallel for collapse(2) default(none) schedule(dynamic) shared(scale,out)
```

That build successfully :)

And I search openmp doc and find :
[In OpenMP, stdout is shared among the threads, so
each thread can execute the printf statement](https://www.cs.usask.ca/~spiteri/CMPT851/notes/openMP.pdf)

- Is that correct?

**Comment by hanatos** [comment]
hi,

this depends on the compiler. openmp is very messy to work with when using
different compilers or their versions. the only portable way to do this
seems to be to use `default(shared)` and not use the explicit `shared`
clause (which is bad practice for other reasons).

your change will likely break compilation for other compilers/versions.

-j.

**Comment by lyd405121** [comment]
Thanks, I will try that!
